name: Exécuter les scripts et envoyer un email

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: |
          python3 -m pip install -r requirements.txt

      - name: Exécuter les scripts d'entraînement et d'évaluation
        run: |
          python3 script/train_evaluate_model.py
          python3 script/test_evaluate_model.py
          python3 script/val_evaluate_model.py

      - name: Archiver le modèle
        run: |
          zip -r model.zip model

      - name: Envoyer un email avec le modèle zippé
        uses: actions/email@v4
        with:
          subject: Résultats du workflow ${{ github.event.repository.name }}
          body: |
            Le workflow ${{ github.event.workflow.name }} s'est terminé avec succès !

            Vous trouverez le modèle zippé en pièce jointe.

            Cordialement,
            L'équipe ${{ github.event.repository.name }}

          to: zogobrice20@gmail.com, evarisfomekong@gmail.com
          attachments: model.zip
  
